version: '3.8'

services:
  django:
    build:
      context: .
    container_name: nature
    ports:
      - "8003:8000"
    volumes:
      - ./nature/media:/app/nature/media
    environment:
      - DEBUG=False
    working_dir: /app/nature
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
