version: '3.8'

services:
  django:
    build:
      context: .
    container_name: nature
    ports:
      - "8003:8000"
    volumes:
      - ./nature/media:/app/nature/media
      - ./nature/database:/app/nature/database
      - ./etetoolkit:/root/.etetoolkit/
    environment:
      - DEBUG=False
    working_dir: /app/nature
    command: daphne config.asgi:application --bind 0.0.0.0:8000

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"