version: '3.8'

services:
  django:
    build:
      context: .
    container_name: nature
    ports:
      - "8000:8000"
    volumes:
      - ./nature/media:/app/nature/media
    environment:
      - DEBUG=True
    command: python nature/manage.py runserver 0.0.0.0:8000
