name: Deploy

on:
  push:
    branches:
      - main

# Définir les jobs
jobs:
  deploy:
    name: Deploy to server
    runs-on: ubuntu-latest
    steps:
      - name: Deploy over SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /home/debian/websites/nature
            git pull
            docker-compose down
            docker-compose build --no-cache
            docker-compose up -d
            docker image prune -f
